### ISSUE TITLE
CHAT

### ISSUE THREAD

**Issue by MotWnb** [alwyn974/MinecraftBOT#18]
If someone says contains % content, the BOT will disconnect

Then an error: "Disconnected: Java. Util. UnknownFormatConversionException: Conversion = '%'

java.util.UnknownFormatConversionException: Conversion = '%'"
![image](https://user-images.githubusercontent.com/98505614/183275794-3be63098-e792-4623-9435-0f69c8bb4cb3.png)

**Comment by alwyn974** [comment]
Fixed in the latest commit of the main branch. I will not release this now.

I will do a release when I have the time with 1.19 support and Microsoft login.

You can build it yourself : 
- Clone the repository
- run `./gradlew shadowJar`
- In the directory `build/libs/` take the jar with `-all.jar`

**Comment by MotWnb** [comment]
**Umm... something wrong** 

PS E:\Downloads\MinecraftBOT-main> ./gradlew shadowJar
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find com.github.GeyserMC:MCProtocolLib:1.18.2-1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://jitpack.io/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://alwyn974.github.io/maven/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://repo.opencollab.dev/maven-releases/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

**Comment by MotWnb** [comment]
**Umm... something wrong** 

PS E:\Downloads\MinecraftBOT-main> ./gradlew shadowJar
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find com.github.GeyserMC:MCProtocolLib:1.18.2-1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://jitpack.io/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://alwyn974.github.io/maven/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://repo.opencollab.dev/maven-releases/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
