### ISSUE TITLE
Can you make it useful to 1.17.1?

### ISSUE THREAD

**Issue by Nanboom233** [alwyn974/MinecraftBOT#2]
It's nice program but it seems it can't connect to 1.17.1 servers.
So please can you make it to be useful to 1.17.1 servers?

> [2021-07-17 22:35:52] [INFO] [MinecraftBOT] Starting MinecraftBOT...

> [2021-07-17 22:43:52] [INFO] [MinecraftBOT] Disconnected: TranslatableComponentImpl{key="Outdated server! I'm still on 1.17.1", args=[], style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}

> [2021-07-17 22:43:52] [INFO] [MinecraftBOT] Version: Spigot 1.17.1, Protocol Version: 756

> [2021-07-17 22:43:52] [INFO] [MinecraftBOT] Player Count: 1000/1000

> [2021-07-17 22:43:52] [INFO] [MinecraftBOT] Players: [§c§lANMotd §r§f§lInfo, §7§m----------, , §b§lOnline: §r§f§l%Online%, §b§lMaxPlayers: §r§f§l30, , §6Donate: §7§l§ourcratf.cn, , §fHave any §6questions§f?, Feel free to §6ask§f me on spigot!, , §7§m----------]

**Comment by alwyn974** [comment]
MinecraftBOT depends on https://github.com/GeyserMC/MCProtocolLib, if they have a branch for 1.17.1 I will do the update as soon as possible

**Comment by Nanboom233** [comment]
And yes they have a branch for 1.17.1
