### ISSUE TITLE
Support 1.19

### ISSUE THREAD

**Issue by Choneas** [alwyn974/MinecraftBOT#23]
Please support the 1.19 version(1.19 1.19.1 1.19.2)

**Comment by Choneas** [comment]
Oh! It Supports! I LOVE YOU! @alwyn974

**Comment by MotWnb** [comment]
Bruh

**Comment by alwyn974** [comment]
@MotWnb 
> Bruh

Please do not comment on closed issues, if you don't have the same problem. This sends me unnecessary notifications, I will lock this issue now.
