### ISSUE TITLE
Add password option to CLI

### ISSUE THREAD

**Issue by Justuser3310** [alwyn974/MinecraftBOT#25]
It will be great.
One script and you on server!

Thank for your project, others or not work or too old.
Good luck!

**Comment by alwyn974** [comment]
Hi, follow the Feature request template please. I need more details about this.
If it's for premium connection it will not be possible to add password option

**Comment by Justuser3310** [comment]
Briefly: Join on spigot(or spigot-like) servers with AuthMe(or AuthMe-like plugins) without manual enter password for Cracked account.

**Is your feature request related to a problem? Please describe.**
Yes, problem - manual enter password every connection with GUI and no possibilities in CLI.

**Describe the solution you'd like**
Add parameter to CLI which allow enter password.

**Comment by alwyn974** [comment]
Added in 1.0.17 
--cmd "/say hello" 
See the README.md for more information

**Comment by Justuser3310** [comment]
See, but... Another problem - There some delay and I can't log in, I guess because bot momentally enter command:
`MC_BOT_COMMAND="/l mypass" MC_BOT_PORT=25664 java -jar MinecraftBOT-1.0.16-all.jar --host somehost.me --user MyNickname`

OS: Linux

**Comment by alwyn974** [comment]
Yeah, there is 2000ms of delay,  it's necessary because without the delay the command is sent before the bot is "really" connected.
I will try another method to send the command on connection

**Comment by alwyn974** [comment]
Yeah, there is 2000ms of delay,  it's necessary because without the delay the command is sent before the bot is "really" connected.
I will try another method to send the command on connection

**Comment by alwyn974** [comment]
Added --cmdDelay time (in ms)

**Comment by Justuser3310** [comment]
Another server, but... It works.
Version - https://github.com/alwyn974/MinecraftBOT/actions/runs/3807998154
