### ISSUE TITLE
[BUG]: Build failed

### ISSUE THREAD

**Issue by MotWnb** [alwyn974/MinecraftBOT#27]
**Build failed**
PS E:\Downloads\MinecraftBOT-main> ./gradlew shadowJar
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find com.github.GeyserMC:MCProtocolLib:1.18.2-1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://jitpack.io/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://alwyn974.github.io/maven/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
       - https://repo.opencollab.dev/maven-releases/com/github/GeyserMC/MCProtocolLib/1.18.2-1/MCProtocolLib-1.18.2-1.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s

**Comment by MotWnb** [comment]
Did you accidentally delete something?

**Comment by MotWnb** [comment]
umm so when will you release this update

**Comment by alwyn974** [comment]
Right now, I don't really have the time.
But why you need to build it from source ? The 1.18.2 release is already available here https://github.com/alwyn974/MinecraftBOT/releases/tag/v1.0.16

**Comment by MotWnb** [comment]
> Right now, I don't really have the time. But why you need to build it from source ? The 1.18.2 release is already available here https://github.com/alwyn974/MinecraftBOT/releases/tag/v1.0.16

ok thx

**Comment by alwyn974** [comment]
Fixed in PR #28
