### ISSUE TITLE
Suggestion: Reconnect Delay

### ISSUE THREAD

**Issue by ROBGUI09** [alwyn974/MinecraftBOT#8]
I have an afk bot on my server but if he get kicked for afk and he cant connect 2 times in a row server refuses connection with "Connection throtted! Please wait before reconnecting"

**Comment by alwyn974** [comment]
I will add this as soon as possible, it's a good feature

**Comment by ROBGUI09** [comment]
i wanted it configurable in stdin....

**Comment by alwyn974** [comment]
--reconnectDelay value
